/* simple.cpp
demonstrating assembly language code generated by the compiler
*/
#include <Windows.h>
void WINAPI wptrsum(int *p1, int *p2, int *p3);
void main() {
	int a, b, c;
	a = 10;
	b = 20;
	wptrsum(&a,&b,&c);
}

void WINAPI wptrsum(int *p1, int *p2, int *p3) { //모든 Windows API는 WINAPI 형식의 함수이다.
	*p3 = *p1 + *p2;
}

//Ctrl+K, Ctrl+F → 들여쓰기