; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

	TITLE	C:\Users\216-15\Desktop\2014440108이용준\20180921Homework1\소스.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?wptrsum@@YGXPAH00@Z				; wptrsum
PUBLIC	_main
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\216-15\desktop\2014440108이용준\20180921homework1\소스.cpp
;	COMDAT _main
_TEXT	SEGMENT
_c$ = -32						; size = 4
_b$ = -20						; size = 4
_a$ = -8						; size = 4
_main	PROC						; COMDAT

; 6    : void main() {

	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 7    : 	int a, b, c;
; 8    : 	a = 10;

	mov	DWORD PTR _a$[ebp], 10			; 0000000aH

; 9    : 	b = 20;

	mov	DWORD PTR _b$[ebp], 20			; 00000014H

; 10   : 	wptrsum(&a,&b,&c);

	lea	eax, DWORD PTR _c$[ebp]
	push	eax
	lea	ecx, DWORD PTR _b$[ebp]
	push	ecx
	lea	edx, DWORD PTR _a$[ebp]
	push	edx
	call	?wptrsum@@YGXPAH00@Z			; wptrsum

; 11   : }

	xor	eax, eax
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN7@main
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 228				; 000000e4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
$LN7@main:
	DD	3
	DD	$LN6@main
$LN6@main:
	DD	-8					; fffffff8H
	DD	4
	DD	$LN3@main
	DD	-20					; ffffffecH
	DD	4
	DD	$LN4@main
	DD	-32					; ffffffe0H
	DD	4
	DD	$LN5@main
$LN5@main:
	DB	99					; 00000063H
	DB	0
$LN4@main:
	DB	98					; 00000062H
	DB	0
$LN3@main:
	DB	97					; 00000061H
	DB	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\216-15\desktop\2014440108이용준\20180921homework1\소스.cpp
;	COMDAT ?wptrsum@@YGXPAH00@Z
_TEXT	SEGMENT
_p1$ = 8						; size = 4
_p2$ = 12						; size = 4
_p3$ = 16						; size = 4
?wptrsum@@YGXPAH00@Z PROC				; wptrsum, COMDAT

; 13   : void WINAPI wptrsum(int *p1, int *p2, int *p3) { //모든 Windows API는 WINAPI 형식의 함수이다.

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 14   : 	*p3 = *p1 + *p2;

	mov	eax, DWORD PTR _p1$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR _p2$[ebp]
	add	ecx, DWORD PTR [edx]
	mov	eax, DWORD PTR _p3$[ebp]
	mov	DWORD PTR [eax], ecx

; 15   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?wptrsum@@YGXPAH00@Z ENDP				; wptrsum
_TEXT	ENDS
END
